# Generated by Django 3.0 on 2020-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genus_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
