# Generated by Django 3.0 on 2020-06-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200623_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='upper',
            new_name='genus',
        ),
    ]
