# Generated by Django 3.0 on 2020-06-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genus_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='owner',
        ),
    ]
