# Generated by Django 3.0 on 2020-06-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_genus_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
